### ISSUE TITLE
assert class exists does not expect interface

### ISSUE THREAD

**Issue by japlavaren** [nextras/orm#472] opened 2020-11-04 16:37 UTC
I have defined list of valid values as
```
* @property string $connectionType {enum IElectricityConnectionType::CONNECTION_*}
```
from interface `IElectricityConnectionType`. problem is, that current version of nextrs orm has check
```
assert(class_exists($className));
```
[source code](https://github.com/nextras/orm/blob/master/src/Entity/Reflection/ModifierParser.php#L230)
In my opinion this line should be changed to
```
assert(class_exists($className) || interface_exists($className));
```
to be working right

**Comment by hrach** [comment] 2020-11-04 18:51
dupe of #471

**Closed by hrach** 2020-11-04 18:51 UTC
Labels: bug
