### ISSUE TITLE
QueryBuilderHelper doesn't treat one has one (directed) relation properly

### ISSUE THREAD

**Issue by MartinLojda** [nextras/orm#98] opened 2015-08-04 10:41 UTC
in normalizeAndAddJoins method - if branch for "one has one" relation is missing.

**Comment by hrach** [comment] 2015-08-14 17:26
There is an else branch, which should work correctly, but probably it isn't. https://github.com/nextras/orm/blob/a03eaaf00374f8c3452699f6a78dfdb96b63f40e/src/Mapper/Dbal/QueryBuilderHelper.php#L139-L142

**Comment by hrach** [comment] 2015-08-18 08:24
I was unable to reproduce query builder failure, although, there is quite big bug in recursive persistance. I added note do doc for v1.1. v1.2 will fix it.

**Comment by hrach** [comment] 2015-08-18 08:26
Oh, I see, the issue has the **important** part in title. You are talking about directed relationship (1:1d) :| I was talking about 1:1.

**Comment by MartinLojda** [comment] 2015-08-18 08:29
Yes, I ment directed relationship and forgot to mention it in the message. Sorry for the confusion.

**Comment by hrach** [comment] 2015-08-18 08:45
@MartinLojda Could you please try the current master? It should be fixed! Thanks for reporting!

**Closed** 2015-08-18 08:44 UTC
Labels: 1-bug, 3-priority-high
