### ISSUE TITLE
calculateCacheKey may produce same key for different parameters

### ISSUE THREAD

**Issue by matej21** [nextras/orm#246] opened 2017-09-13 12:29 UTC
Hi, 
I use `marc-mabe/php-enum` for enums in php and when I pass it to a findBy method, nextras/orm may reuse entity iterator from a cache. It happens because [orm uses json_encode](https://github.com/nextras/orm/blob/9df3fe627b357f765393fb37affdc29c802ec946/src/Mapper/Dbal/RelationshipMapperOneHasMany.php#L299) to calculate a cache key and `Enum` does not implement JsonSerializable, so PHP exports all public properties - which is none.

Not sure how to solve it, maybe enforce to implement JsonSerializable on object parameters? or use `spl_object_hash` instead?

**Comment by hrach** [comment] 2017-09-13 12:51
spl_object_hash could return same hashes for different objects, so I suspect that the problem could persist. What about using php's native serialize?

**Comment by hrach** [comment] 2020-04-26 19:49
I have written a test and the problem is not there (for now). The enums are already "prepared" for SQL -> e.g. their name is used in this phase now. (When using them correctly with property wrapper). This may have been different back in 2017, but closing as resolved now.

**Closed by hrach** 2020-04-26 19:49 UTC
Labels: 1-bug
